version: "3.8"
services:
  db:
    image: postgres:12.3-alpine
    container_name: postgres
    env_file:
      - .env
    ports:
      - 5432:5432
    volumes:
      - postgres:/var/lib/postgresql/data
    networks:
      - backend

  nginx:
    image: nginx:1.19.2-alpine
    container_name: nginx
    ports:
      - 80:80
    volumes:
      - ./nginx.dev.conf:/etc/nginx/conf.d/default.conf
    networks:
      - frontend

  app:
    build:
      context: ../
      dockerfile: docker_rails_env/Dockerfile
    image: shelter_app
    container_name: shelter_app 
    entrypoint: /usr/bin/entrypoint.sh
    env_file:
      - .env
    command: bash -c "rm -f tmp/pids/server.pid && bundle exec rails s -p 3000 -b '0.0.0.0'"
    volumes:
      - ..:/shelter
    networks:
      - frontend
      - backend
    stdin_open: true
    tty: true

volumes:
  postgres:

networks:
  backend:
  frontend:
